### ISSUE TITLE
Implement hiera support

### ISSUE THREAD

**Issue by divad** [southampton/cortex#100]
We should implement hiera support. This means adding a 'hiera' yaml column to the puppet_nodes table where per-node hiera variables would be kept. An additional editor would be added to the nodes page for Hiera YAML editing which would simply allow the node to set whatever variables it wants.

Per-group hiera support is not possible as hiera does not (and cannot) know what groups a system is in. Sad times. This is why hiera sucks and why integration with the ENC for hiera would have been far, far more logical. Sadly, PuppetLabs dun screwed it up.</rant>

We should also add a 'puppet_roles' table. A Puppet role would allow us to set Hiera variables AND include classes. This would allow us to set the tuned profile for example on a system via hiera variables from a role for say "oracle" rather than having to do horrible complicated if statements.for setting the tuned profile during a catalog compilation. 

We would thus need to add a 'role' column to the 'puppet_nodes' table as well which would allow us to select the role for the node.

**Comment by jrdan** [comment]
No plans to deploy Hiera at this time.
