### ISSUE TITLE
API for service now to call

### ISSUE THREAD

**Issue by divad** [southampton/cortex#12]

**Comment by jakemalley** [comment]
Can this be closed? Service Now doesn't really need to call Cortex, all the data required is pushed to Service Now?

**Comment by claytonpeters** [comment]
Almost, yes - I'll close this once I've done the student VM workflow, as that's sort of what this has turned out being.

**Comment by jakemalley** [comment]
Service management don't have any specific requirement for an API to call currently, with the student vm stuff and the restplus api I am closing this.
