### ISSUE TITLE
Create production VM for Cortex

### ISSUE THREAD

**Issue by claytonpeters** [southampton/cortex#13]

**Comment by divad** [comment]
This shouldn't be on the bug tracker for the /code/

**Comment by claytonpeters** [comment]
pyVmomi 6.0 requires Python 2.7, so this will need installing from RH SCL. Need to test this in dev.

**Comment by claytonpeters** [comment]
Internal ticket INC0258466 created for this

**Comment by claytonpeters** [comment]
VMs created by ESM
