### ISSUE TITLE
Add "Expand..." link to IP routes/addreses on System Overview page

### ISSUE THREAD

**Issue by claytonpeters** [southampton/cortex#145]
Most VMs end up with lots of routes and addresses, which makes the Network section of the Overview page quite big. Maybe consider showing only the first one, and adding a link to show them all if necessary.

**Comment by jakemalley** [comment]
Added this into Pre-Prod. See the PR #147

**Comment by jrdan** [comment]
Fixed with scrollable input in 633e2592bdd87e05a4784bcf3cf246a611e5d34c
