### ISSUE TITLE
Change alignment of "Power Control" buttons on the system overview page.

### ISSUE THREAD

**Issue by jakemalley** [southampton/cortex#146]
The power control buttons on the system/overview page are quite bunched up, especially on widescreen, can we increase the spacing between them?

**Comment by claytonpeters** [comment]
I spread them out slightly in pre-prod earlier on, but I agree, they might need a bit more still

**Comment by jakemalley** [comment]
Don't know if changes made in 32b9f91877a1ba16f6d3d5e158141f283a8bdcd3 solves the problem but I think it looks better.

**Comment by jrdan** [comment]
looks good
