### ISSUE TITLE
FR: Rubrik garbage collect unassinged objects

### ISSUE THREAD

**Issue by jrdan** [southampton/cortex#184]
When a VM enters the unmanaged state (Do Not Protect or decommed) it's backups will reside on Rubrik disk until it is manually cleaned. It is desirable for these backups to be GCed when the previously applied policy reaches its retention timer.

Potential approach would be to log the previous retention period and use a scheduler to remove old backups when the unmanaged VM backups exceed the previous retention period.

**Comment by jakemalley** [comment]
This has been fixed in the latest version of Rubrik - VMs decommed keep their last SLA domain and backups automatically expire as per that policy.
