### ISSUE TITLE
Puppet Statistic Inconsistencies 

### ISSUE THREAD

**Issue by jakemalley** [southampton/cortex#225]
There are some inconsistencies with the Puppet node stats displayed in Cortex, due to the update to the pypuppetdb module. For example: on the dashboard (uses a direct query) the number of failed nodes is displayed as 6 currently. Grafana and the Puppet dashboard show the failed nodes as 2 (I think this should be the right number, as we were going with noop overrides a failed). When clicking "failed" on the puppet dashboard or searching "failed" in the nodes list 3 boxes appear. Guess we need to decide which one to use and fix the direct Puppet query for the dashboard.

**Comment by claytonpeters** [comment]
Yep, I spotted this yesterday too, but given the upgrade overran by three hours, I never got round to creating a bug. Should be a trivial fix, just need to move some code around.

**Comment by jakemalley** [comment]
Yep, I only created an issue because I noticed it when having a quick look this morning and didn’t want to forget... As you said easy and trivial to fix. I’ll do it tomorrow afternoon and created a branch called v4-fixes and merge it into that.

**Comment by jakemalley** [comment]
Fixed in v4.0.2
