### ISSUE TITLE
Add VMware folder selection to buildvm workflow

### ISSUE THREAD

**Issue by claytonpeters** [southampton/cortex#227]
Currently all VMs go in to a default folder, and users are meant to move them manually... but they don't. We already cache the VMware folder information, so we might as well make this folder selectable. This is mostly a UI change, with a small amount of code change to use what's selected rather than the default.

**Comment by jakemalley** [comment]
We need to change the way folders are selected and displayed to handle multiple folders with the same name.

**Comment by jakemalley** [comment]
Fixed in v4-fixes.
