### ISSUE TITLE
Task: _rubrik_policy_check - failed

### ISSUE THREAD

**Issue by rh1f10** [southampton/cortex#316]
Hi,

I've ran the Rubrik check policy job today, after Gary raised it to me, and I see that the checks appear to work but at the bottom of the task we get:

 The task failed because an exception was raised: NameError - name 'app' is not defined

Task ended at 2019-08-19 10:39:05. Elapsed Time: 0:00:06

Dunno whats going on here. I have made some changes today to "unprotect" a load of VMs with the following prefixes:

svm
play
build
test
sds

Not sure if its related or not.

Cheers,

Ryan

**Comment by claytonpeters** [comment]
From the logs it looks like the Rubrik API is returning an unusal status code (which is the original cause of the error), but the error handling goes awry, which causes the task to fail. I'll double-check what HTTP error codes we're meant to be handling.

**Comment by claytonpeters** [comment]
Right, I've fixed this in a separate branch. I'll get it merged in to the next release.

**Comment by jakemalley** [comment]
Is this fixed in v5-fixes?

**Comment by claytonpeters** [comment]
Fixed in v5.2.1
