### ISSUE TITLE
Puppet classify is broken when submitting invalid data

### ISSUE THREAD

**Issue by jakemalley** [southampton/cortex#327]
483dbfdda2626b9568fe9c4d811610141645d9a6 changed a line to:
`var dictionary = {{ variable_names | tojson | safe }} // will hold all the keywords`
if `variable_names` is invalid this fails and causes an exception. 

reproduced by submitting `my_module::test` (no trailing `:`)

**Comment by claytonpeters** [comment]
Fixed in release v5.2.1
