### ISSUE TITLE
Request: Add Pre/Post script to all Linux machines on build

### ISSUE THREAD

**Issue by rh1f10** [southampton/cortex#350]
Yo,

We have now completed work on the UOS Rubrik puppet module which automatically creates a framework to automatically run any pre/post/post script within a specific directory on our build.

We want to have any linux machine that is built, automatically execute the following scripts:

PRE-BACKUP:  /etc/soton/rubrik/pre-backup.sh

POST-SNAPSHOT:  /etc/soton/rubrik/post-snapshot.sh

POST-BACKUP:  /etc/soton/rubrik/post-backup.sh

These will in turn runs script nested further into the directory structure. If nothing exists, they return with success message.

The JSON required, at least from an ugly powershell perspective, is:

$settings = @{ 
                "preBackupScript" = @( 
                @{ 
                "scriptPath" = /etc/soton/rubrik/pre-backup.sh
                "timeoutMs" = 60000
                "failureHandling" = continue
                } 
                )
                "postSnapScript" = @( 
                @{ 
                "scriptPath" = /etc/soton/rubrik/post-snapshot.sh
                "timeoutMs" = 60000
                "failureHandling" = continue
                } 
                ) 
                "postBackupScript" = @( 
                @{ 
                "scriptPath" = /etc/soton/rubrik/pre-backup.sh
                "timeoutMs" = 60000
                "failureHandling" = continue
                } 

This needs to hit the /vmware/vm/{id}  PATCH endpoint in Rubrik:
https://rubrik.soton.ac.uk/docs/v1/playground/#!/47vmware47vm/updateVm

This can be done at the same time that Cortex automatically allocates an SLA domain to a VM (assuming by that point you have the rubrik internal Vmware VM ID?).

Any questions, give us a shout.

Cheers,

Ryan

**Comment by jakemalley** [comment]
Fixed in v6
