### ISSUE TITLE
Flask-RESTPlus should be considered unmaintained.

### ISSUE THREAD

**Issue by jakemalley** [southampton/cortex#364]
This project has been forked to Flask-RESTX and will be maintained by by the python-restx organization. Flask-RESTPlus should be considered unmaintained. https://github.com/python-restx/flask-restx

**Comment by claytonpeters** [comment]
Tested replacing this on another project yesterday - was all trivial.

**Comment by jakemalley** [comment]
"trivial"

**Comment by claytonpeters** [comment]
Was it not trivial? :stuck_out_tongue:

**Comment by jakemalley** [comment]
Fixed in v6
