### ISSUE TITLE
Create 'New VMs' folder in VMware and put new vms in there

### ISSUE THREAD

**Issue by claytonpeters** [southampton/cortex#61]

**Comment by divad** [comment]
Cache table and caching code added to cache all folders in all data centers.

Now I will write a way to list them...somehow...in a workflow. Maybe.

**Comment by claytonpeters** [comment]
BUG: This is causing IntegrityErrors on the import currently. Probably a cache deletion issue. Also I think the vmware_clone_vm code for putting it into the folder is wrong...

**Comment by claytonpeters** [comment]
Resolved the IntegrityError problem

**Comment by divad** [comment]
Resolved in latest version.
