### ISSUE TITLE
Ping ip addresses in case infoblox doesnt know if the IP address is actually in use

### ISSUE THREAD

**Issue by divad** [southampton/cortex#7]
@claytonpeters Gary raised this issue, discuss with you later.

**Comment by divad** [comment]
For standard VM workflow only. 

Will add a "check_ip_icmp" or something function to NeoCortexLib.

**Comment by claytonpeters** [comment]
wontfix reasoning:

ICMP Ping requires root privileges (and calling /bin/ping seems a bit sketchy). TCP ping isn't a good way of testing. IPtrack was considered, but what defines a box as not having been seen recently - what if the server has just been off for a few hours?
