### ISSUE TITLE
Add expiration functions to Cortex

### ISSUE THREAD

**Issue by claytonpeters** [southampton/cortex#86]
1. Add an expiration date option to the Sandbox workflow
2. Add an expiration date option to the normal workflow, but hidden/disabled
3. Create a new scheduled system task that runs every 15 minutes to switch off expired systems
4. Create a new "Expired Virtual Machines" view which lists systems which have actived linked virtual machines (i.e. the link is there and the VM is not deleted).

**Comment by divad** [comment]
Updated description to reflect new requirements.

**Comment by jrdan** [comment]
Still need to: 

- Add the feature in a hidden form in the normal workflow
- Setup VM destruction after a given period.
- Create Expired VMs view

**Comment by claytonpeters** [comment]
This has now been completed.
